[package]
name = "pdf2scrapbox"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }
indoc = "2.0"
dotenv = "0.15.0"
gyazo-api = "0.2.0"
